name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]

    runs-on: ${{matrix.os}}
    
    steps:
    - name: runner info
      run: echo "running on $RUNNER_OS"
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: install core dependencies
      if: runner.os != 'Windows'
      run: |
        echo "runner os: $RUNNER_OS"
        sudo apt update
        sudo apt install ninja-build libxi-dev libglx-dev
        
    - name: install llvm/clang
      uses: KyleMayes/install-llvm-action@v2.0.3
      with:
        version: "16"
      
    - name: configure
      run: ./configure.py --debug
      
    - name: compile
      run: ninja -C build
