name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: install core dependencies
      run: |
        sudo apt update
        sudo apt install ninja-build
        
    - name: install llvm/clang
      uses: KyleMayes/install-llvm-action@v2.0.3
      with:
        version: "16"
      
    - name: configure
      run: ./configure.py --debug
    - name: compile
      run: ninja -C build
